### ISSUE TITLE
Error - Unexpected token function

### ISSUE THREAD

**Issue by dannycallaghan** [Annihil/github-spray#4]
Hi

This looks great by the way. Just tried pushing the initial commit with:

`github-spray -t <text> --multiplier <factor> --push --origin <github_repository_url>`

And get the following error:

`exports.getParentTerminalInfo = async function getParentTerminalInfo( callback ) {
                                      ^^^^^^^^
SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous>(/Users/dannycallaghan/.nvm/versions/node/v6.11.0/lib/node_modules/github-spray/node_modules/terminal-kit/lib/termkit.js:53:26)`

Tried in iTerm and Terminal in OSX 10.14.2. Is this a Node version issue? I'm on v6.11.0.

**Comment by dannycallaghan** [comment]
UPDATE

Switched to node v8.12.0 and ran the push again. Now get:

`const max = Math.max(...matrix.flat());
                                   ^

TypeError: matrix.flat is not a function
    at Object.<anonymous> (/Users/dannycallaghan/.nvm/versions/node/v8.12.0/lib/node_modules/github-spray/index.js:94:36)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3`

**Comment by Annihil** [comment]
Hi, yes a recent version of Node is required, try updating it with Homebrew  
```
brew update
brew upgrade node
```

**Comment by dannycallaghan** [comment]
Yeah, confirmed. Upgraded to 10.15.1 (LTS) and still no dice, but then upgraded to 11.9.0 and it works fine. Great work.
