### ISSUE TITLE
Error : 'touch' is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by SaadKhanMalik** [Annihil/github-spray#6]
Tried running it LTS 10.15.3  and current 12.3.1, no game.
Also ran it in the root. and got Status: 1.
would love some help!
```
C:\Users\saad_\AppData\Roaming\npm\node_modules\github-spray> github-spray -t hello -m 10 -p -o https://github.com/SaadKhanMalik/Project-1.git
'touch' is not recognized as an internal or external command,
operable program or batch file.
child_process.js:661
    throw err;
    ^

Error: Command failed: touch spray-8154c2ea2700/readme.md
'touch' is not recognized as an internal or external command,
operable program or batch file.

    at checkExecSyncError (child_process.js:621:11)
    at execSync (child_process.js:658:15)
    at Object.<anonymous> (C:\Users\saad_\AppData\Roaming\npm\node_modules\github-spray\index.js:85:1)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
    at internal/main/run_main_module.js:17:11 {
  status: 1,
  signal: null,
  output: [
    null,
    <Buffer >,
    <Buffer 27 74 6f 75 63 68 27 20 69 73 20 6e 6f 74 20 72 65 63 6f 67 6e 69 7a 65 64 20 61 73 20 61 6e 20 69 6e 74 65 72 6e 61 6c 20 6f 72 20 65 78 74 65 72 6e ... 46 more bytes>
  ],
  pid: 12028,
  stdout: <Buffer >,
  stderr: <Buffer 27 74 6f 75 63 68 27 20 69 73 20 6e 6f 74 20 72 65 63 6f 67 6e 69 7a 65 64 20 61 73 20 61 6e 20 69 6e 74 65 72 6e 61 6c 20 6f 72 20 65 78 74 65 72 6e ... 46 more bytes>
}
```

**Comment by Annihil** [comment]
Are you using Windows Subsystem for Linux?

**Comment by SaadKhanMalik** [comment]
I am using native windows.

**Comment by Annihil** [comment]
Try `npm install -g touch`
